language: go

go:
  - "1.11"
  - "1.11.x"
  - master

before_install:
  - sudo apt-get update
  - sudo apt-get install -y autoconf automake libtool curl make g++ unzip
  - git clone https://github.com/protocolbuffers/protobuf.git && cd protobuf && git submodule update --init --recursive && ./autogen.sh
  - make install

script: make all