language: go

services:
  - docker

before_install:
  - docker build -t protogen-environment:latest .
  # - sudo apt-get update
  # - sudo apt-get install -y autoconf automake libtool curl make g++ unzip
  # - git clone https://github.com/protocolbuffers/protobuf.git && cd protobuf && git submodule update --init --recursive && ./autogen.sh && cd ..
  # - make install

script:
  - docker run -v $(pwd):/go/src/github.com/zeeraw/protogen --rm protogen-environment:latest make all 

git:
  submodules_depth: 10