language: go

services:
  - docker

before_install:
  - docker build -t protogen-environment:latest .

script:
  - docker run -v $(pwd):/go/src/github.com/zeeraw/protogen --rm protogen-environment:latest make all 

git:
  submodules_depth: 10